library(data.table)
library(dplyr)
unzip("exdata_data_household_power_consumption.zip")
file <- fread("household_power_consumption.txt", na.strings = "?")
newfile1 <- filter(file, Date == "1/2/2007"| Date == "2/2/2007")
rm(file)
png(filename = "plot1.png")
dev.cur()
hist(newfile1$Global_active_power, xlab = "Global Active Power (kilowatts)", main = "Global Active Power", col = "red")
dev.off()
